version: '2.4'
services:
  jenkins:
    image: 'jenkins/jcas:test'
    build: './'
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "wget", "http://jenkins:8080/manage", "--spider" ]
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 5s

  bats:
    image: 'dduportal/bats:1.0.0'
    volumes_from:
      - jenkins:ro
    volumes:
      - ./tests:/my-tests
    command: [ "/my-tests" ]
    depends_on:
      - jenkins
